repos:
  - repo: https://github.com/terraform-linters/tflint
    hooks:
      - id: tflint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
  - repo: https://github.com/bridgecrewio/checkov
    hooks:
      - id: checkov
