name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 6 * * *' # Runs at 6 AM UTC daily

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.4  # Or a valid version (1.9.8 might not exist yet)

      - name: Terraform Format Check
        working-directory: environments/dev
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/dev
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: environments/dev
        run: terraform apply -auto-approve tfplan